"""initial tables

Revision ID: 41f774ecaa9d
Revises: 
Create Date: 2026-06-07 00:29:02.913144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41f774ecaa9d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('wid', sa.BigInteger(), nullable=False),
    sa.Column('ean', sa.BigInteger(), nullable=False),
    sa.Column('manufacturing_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('wid')
    )
    op.create_index(op.f('ix_products_ean'), 'products', ['ean'], unique=False)
    op.create_index(op.f('ix_products_expiry_date'), 'products', ['expiry_date'], unique=False)
    op.create_table('upload_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='jobstatus'), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('processed_rows', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verification_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wid', sa.BigInteger(), nullable=False),
    sa.Column('operator_id', sa.String(length=255), nullable=True),
    sa.Column('image_path', sa.String(length=1000), nullable=True),
    sa.Column('db_mfg_date', sa.Date(), nullable=True),
    sa.Column('db_expiry_date', sa.Date(), nullable=True),
    sa.Column('ai_mfg_date', sa.Date(), nullable=True),
    sa.Column('ai_expiry_date', sa.Date(), nullable=True),
    sa.Column('ai_match_status', sa.Enum('match', 'mismatch', 'skipped', 'error', name='aimatchstatus'), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_logs_verified_at'), 'verification_logs', ['verified_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_logs_verified_at'), table_name='verification_logs')
    op.drop_table('verification_logs')
    op.drop_table('upload_jobs')
    op.drop_index(op.f('ix_products_expiry_date'), table_name='products')
    op.drop_index(op.f('ix_products_ean'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
